apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
spec:
  scaleTargetRef:
    name: nginx-deployment
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"