apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
  namespace: default
  annotations:
    # Explicitly exclude CPU scaling since HPA handles it
    keda.sh/paused-replicas: "0"
spec:
  scaleTargetRef:
    name: nginx-deployment
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: memory
    metricType: Utilization
    metadata:
      value: "80"  # Scale based on memory usage instead of CPU