apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: 'https://github.com/Rookiep/jenkins-nginx-k8s-pipeline.git'
    path: k8s
=======
    repoURL: 'https://github.com/Rookiep/jenkins-nginx-k8s-pipeline.git'  # Update with real Git URL
>>>>>>> 742366a66ff1236afc3926551206ab0b1c3a063e
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
